### PR TITLE
Made The Dark Theme Really Dark

### PR DESCRIPTION
**Pull request by tsujan**
Revamped parts of the theme.

### CODE REVIEW

**Comment by jleclanche** [comment]
Comparison screenshots?

**Comment by tsujan** [comment]
Sorry, I didn't have time for that and now I'm not under LXQt. Please just try it!

**Comment by stefonarch** [comment]
schermata01


Issues I found :
 - kbindicator enabled/disabled is not styled

- search results list:

> #MainMenu ActionView::item:selected, ActionView::item:hover {
    background: #640b0c;
    color: white;
}

hover not works here , better only :

> #MainMenu ActionView::item:hover {
   background: #640b0c;
   color: white;
}

 this avoids having two items highlighted at the same time

- menu and program list in runner are not styled, program list is tricky, I'll do a test.

I would decrease transparency a little bit in taskbar buttons, with bright background text is not readable well.

**Comment by tsujan** [comment]
@stefonarc, thanks for testing. I'll make changes in the same PR.

BTW, Ambiance's selected menu-items seems like a mess to me. Is it so there too?

**Comment by stefonarch** [comment]
I'll have a look in Ambiance.
 In the meantime I saw the comments in runner.qss, I made similar ones in my themes, until some day I found out some working code, this for your   commit here:

>#commandList {
   border: 1px solid #1899da;
   border-top:none;
   background:#c3c3c3;
   alternate-background-color:#dcdcdc;
   selection-color: white;
   selection-background-color:#640b0c;
}
#commandList::item /*bug? Is not considered at all, same with QListView Item*/{
   margin: 2 px;
   padding: 2px;
   color:red; 
}

I found no way for color=something, except selection, and I have no idea here the reddish hover color comes from here...

**Comment by tsujan** [comment]
Wow! That's exactly what I did here a few minutes ago (offlne).

**Comment by stefonarch** [comment]
> Wow! That's exactly what I did here a few minutes ago (offlne).

:)

About the higlighted items in search results: Maybe it's better to leave both selected and hover.
In ambiance there are quiet different, this is not bad, so one can see which application wopuld start hitting enter key.

But there is a strange inconsistency in hovering by mouse or by arrow keys, one acts on "hover" the other on "selected",  and this underline I never managed to get rid of, it comes from the code I think.

Screen:
schermata02

**Comment by tsujan** [comment]
I don't have that underline here.

**Comment by tsujan** [comment]
OK, I made the menus a little translucent, fixed kbindicator and added style to runner. The runner list can't be styled completely, so I left it to the active widget style to prevent unreadable text.

**Comment by tsujan** [comment]
@palinek 
Do you have any idea why the runner list can't be styled. It's not a big deal though.

**Comment by stefonarch** [comment]
> @palinek 
 Do you have any idea why the runner list can't be styled. It's not a big deal though.

There is another item that cannot be styled: the title text-color  in panel popup (panel|clock) clicking on clock, so in some themes there were issues with invisible titles.

**Comment by tsujan** [comment]
> There is another item that cannot be styled: the title text-color in panel popup (panel|clock) clicking on clock

I don't see the issue here. Could you show a screenshot?

**Comment by stefonarch** [comment]
> I don't see the issue here. Could you show a screenshot?

You are right, no issue, looking at the dark code commit I see

> QMenu QToolButton {
}

For some reason I never stumpled upon that piece, I guess in most themes it's just missing, thanks.

**Comment by tsujan** [comment]
Oh, those titles are (pressed) tool buttons and yes, I styled them too. They're a KDE invention.

**Comment by tsujan** [comment]
OK, I fixed Ambiance's issue too. This PR is completed, I think.

**Comment by Esclapion** [comment]
Tested here, and it works, thanks for your work. :-)

Only the selection is red and doesn't fit with my gtk theme, but it's useable.

**Comment by tsujan** [comment]
> Only the selection is red and doesn't fit with my gtk theme

That's why I don't use any theme for menus but let Kvantum draw them (with larger icons). Anyway, tastes differ.

**Comment by palinek** [comment]
> Do you have any idea why the runner list can't be styled. 

Sorry, I didn't follow the discussion here during the weekend... Did you managed it or should I still check something?

**Comment by tsujan** [comment]
> Sorry, I didn't follow the discussion here during the weekend... Did you managed it or should I still check something?

Everything is OK except that, apparently, the runner list isn't stylable. Is that intended?

**Comment by palinek** [comment]
> Everything is OK except that, apparently, the runner list isn't stylable. Is that intended?

Are you talking about the lxqt-runner? The styling is done e.g. here: https://github.com/lxde/lxqt-common/blob/master/themes/frost/lxqt-runner.qss#L65

**Comment by tsujan** [comment]
> Are you talking about the lxqt-runner? The styling is done e.g. here: https://github.com/lxde/lxqt-common/blob/master/themes/frost/lxqt-runner.qss#L65

Yes! The problem is that styling is incomplete. For example, text color or the alternative background color can't be changed.

**Comment by stefonarch** [comment]
> Everything is OK except that, apparently, the runner list isn't stylable. Is that intended?
It's styled by widget style, but maybe a [hardcoded dark styling](Everything is OK except that, apparently, the runner list isn't stylable. Is that intended?) is to prefer?

Example dark-red kvantum:
schermata04

**Comment by palinek** [comment]
> Yes! The problem is that styling is incomplete. For example, text color or the alternative background color can't be changed.

Hm... I don't know why the `::item` subcontrol isn't taken into account. But the e.g. ` alternate-background-color` is working in the `#commandList` selector...

**Comment by palinek** [comment]
> > Yes! The problem is that styling is incomplete. For example, text color or the alternative background color can't be changed.

> Hm... I don't know why the ::item subcontrol isn't taken into account. But the e.g. alternate-background-color is working in the #commandList selector...

It might be a wrong logic in the liblxqt's `HmlDelegate` https://github.com/lxde/liblxqt/blob/master/lxqthtmldelegate.cpp#L49

**Comment by tsujan** [comment]
> But the e.g. alternate-background-color is working....

Yes, it works. Sorry for my bad memory; I played with it yesterday. The problem was that the text color and, perhaps, the selected item background weren't set, as far as I remember.

**Comment by tsujan** [comment]
> It might be a wrong logic in the liblxqt's HmlDelegate https://github.com/lxde/liblxqt/blob/master/lxqthtmldelegate.cpp#L49

Yes, it sould be that. I'm busy right now but I'll examine it too.

**Comment by tsujan** [comment]
My work on this PR is finished. Please merge it if it seems OK to you! In short, the dark theme and Ambiance's selected menu-items are fixed.  Ambiance was so before:

ambiance

Now it's OK.

**Comment by paulolieuthier** [comment]
Results are really good, I liked the new secondary color. Two minor issues:

* The second submenu has different background and transparency. This is not a problem, but maybe wasn't intentional.

submenu

* The search view's items are too big, as is the clear text icon using Breeze.

search_menu

**Comment by paulolieuthier** [comment]
In Ambiance the menu is much longer now, and that may be a problem in low resolution screens. Besides, the submenus' item's texts are too close to theirs icons.

screenshot_20161004_084914

**Comment by stefonarch** [comment]
I've seen this huge icon in my themes, it depends on margin= bigger than 2 or 3, but here actually I doncannot see it with breeze, but the search result list is bigger than in menu.

For ambiance I propose:

> #MainMenu QMenu::item {
>     color: #f2f1f0;
>     padding: 7px 40px 7px 30px;
> }
>  #MainMenu ActionView::item {
>     padding: 6px 0px;
>  }

**Comment by tsujan** [comment]
> The second submenu has different background and transparency

Here, all menus have the same translucency, as they should. What you see is strange to me!

> The search view's items are too big... In Ambiance the menu is much longer now,...

Tastes differ. No one could make a theme liked by everyone. Please feel free to make any changes you want (as far as nothing is broken)! it's fine with me :)

**Comment by tsujan** [comment]
BTW, the real Ambiance menus are like what I made. I'm familiar with Ambiance because of 2 Kvantum themes. I didn't make other changes because I wanted to respect the original work.

**Comment by tsujan** [comment]
These are what Ambiance menus look like (KvAmbiance):

ambiance

I could make a theme much like Ambiance but thought it was better not to engage with this part of LXQt ;)

**Comment by tsujan** [comment]
@paulolieuthier 

I logged into LXQt and made a few changes according to your tatse. But I saw that the Ambiance you saw was not the Ambiance I'd made. Mine is so (I just made the vertical spaces smaller, as you wanted; no other change):

amb

**Comment by paulolieuthier** [comment]
I'll test again tonight. Anyway, it's fine to merge it.

**Comment by tsujan** [comment]
OK! If you think that Ambiance's menu-item vertical padding is too small now,  change `5px` in:
````
#MainMenu QMenu::item {
    color: #f2f1f0;
    padding: 5px 40px 5px 24px;
  }
```
Please merge it yourself! Thanks!

**Comment by agaida** [comment]
GTM

**Pull request merged**
