### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by agaida**
ignore dir .kdev4

### CODE REVIEW

**Comment by paulolieuthier** [comment]
IMO ignoring KDevelop's project file as well is a good idea. So `*.kdev4` instead of `/.kdev4/`.

**Comment by agaida** [comment]
does it catch the dir?

**Comment by paulolieuthier** [comment]
Yes.

**Comment by jleclanche** [comment]
Squash please and updated to `*.kdev4`.

**Pull request closed without merging**
