### PR TITLE
startlxqt: Consider pre-exising LXDE OB config also

### PR DESCRIPTION
**Pull request by palinek**
ref. lxde/lxqt#1057

### CODE REVIEW

**Comment by paulolieuthier** [comment]
GTM.

**Comment by pmattern** [comment]
Works as expected. GTM.

**Comment by palinek** [comment]
Yes, but looking at it the second time raises another question.... which file should have higher priority?

Logical should be:
- old LXQt configuration (rc.xml)
- old LXDE configration (lxde-rc.xml)
- old "plain" configuration (rc.xml)

But how can we know if the rc.xml is just a plain openbox configuration or LXQt's?

**Comment by pmattern** [comment]
(In "old LXQt configuration [...]" it should be lxqt-rc.xml, no?)

If I'm not mistaken distinguishing whether a preexisting `rc.xml` is the stock Openbox one or was customized from an LXQt session has relevance only when LXQt components which didn't use the custom `lxqt-rc.xml` *and* LXDE sessions were run before. But in this particular case the informations displayed by `xmessage` allow for realizing what happened very well making it easy for users to adjust the configuration files if needed.
The latter applies as well if users shouldn't be happy with prioritizing preexisting `lxde-rc.xml` over preexisting `rc.xml`.
So all in all I still think the behaviour as seen with cbd5ef2c is alright and does not need any further tweaking.

**Comment by palinek** [comment]
> ...does not need any further tweaking.

OK. merging...

**Pull request merged**
