### PR TITLE
Updated german translation, replaced Qt4 by Qt in all xsession/translati...

### PR DESCRIPTION
**Pull request by ThomasVie**
...ons
Moved xxx_de_DE.desktop files to xxx_de.desktop. This enables a translation for the other german speaking regions, too.

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm

**Comment by luis-pereira** [comment]
Tested it and it's Ok, I think. It's hard to review because it does 3 things:
* Moves/Removes de_DE
* Updates _de translations
* Replaces Qt4 by Qt in all translations

The first two are probably related but to the last one. Clean as possible commits makes it simpler for everybody.

**Comment by ThomasVie** [comment]
Sorry for the inconvenience. Next time I promise to split the commits.

**Comment by luis-pereira** [comment]
Thanks @ThomasVie

**Pull request merged**
