### PR TITLE
Replace lxqt-rc.xml with latest openbox version

### PR DESCRIPTION
**Pull request by stefonarch**
Changed  also browser shortcut  form konqueror to  qupzilla.
Solves https://github.com/lxde/lxqt/issues/1032

### CODE REVIEW

**Comment by pmattern** [comment]
A shortcut to launch a web browser is available in lxqt-globalkeys. Currently it's relying on `xdg-open` which may not be the perfect solution but I think this is nevertheless the way to go. Setting the browser that way is window manager agnostic and may hence help avoid setting browsers' shortcut both by LXQt and the window manager.
So shouldn't we just drop the section setting the browser shortcut in lxqt-rc.xml altogether?

Regarding the font size I personally think the rather tiny ones are alright but these can be tweaked by ObConf[-Qt] easily so I'd certainly not be opposed to adopting the changes you propose.

**Comment by stefonarch** [comment]
I just stumpled upon Konqueror in this section (wondering who put that dino in) and didn't think further, +1 for just removing the section or maybe  better commenting it out.

There are also other possible things we could change like the number of default desktop, personally I know nobody not-geek who uses any of them. In the old version there were 2, now 4, I'd vote for 2.

**Comment by pmattern** [comment]
Yeah. So I'd so go ahead and update this PR accordingly. If you should need help you may ask here or on freenode #lxde.

**Comment by stefonarch** [comment]
Commented out application section and I've changed also the name in the first comment to lxqt-rc.xml

**Comment by pmattern** [comment]
There's a syntax error in the browser section right now. The comment is meant to frame the keybind section only. So the string to mark its end must not be in line 312 but above line `</keyboard>`.
While at it you could indent the string to ease readability.
Also, I'd propose to modify the explanation a bit and change its format to ease reading.
All in all it could be something like this
```
  <!-- Keybindings for running applications.
   Commented out as application shortcuts should be  handled by
   lxqt-globalkeys in LXQt sessions.
  <keybind key="W-q">
    <action name="Execute">
      <startupnotify>
        <enabled>true</enabled>
        <name>Qupzilla</name>
      </startupnotify>
      <command>qupzilla</command>
    </action>
  </keybind>
  -->
```

**Comment by paulolieuthier** [comment]
Is there anything missing (or to be tested) besides this fix?

**Comment by pmattern** [comment]
@paulolieuthier 
Basically no.
When the changes posted in my previous comment - one a must as the syntax is currently wrong, the rest to ease reading - are applied the file works as expected. Just wanted to leave this to @stefonarch as he opened the PR.
The only addition I came across in the meantime is we should probably set the theme to `Onyx` as this is fitting better default LXQt theme `Frost`.

**Comment by stefonarch** [comment]
Replaced, but I don't think it's a syntax error, if it is there are others in the original, see lines 63, 137 and 740

**Comment by pmattern** [comment]
I'm sorry but this is wrong again. This time you dropped tag `</keyboard>` at the end of the section.

While at it, I'd propose to replace theme `Clearlooks` with `Onyx` for the reason stated above.

**Comment by stefonarch** [comment]
Hopefully done right now (it's definitily too hot here), desktops were 2 in our old file, so this does not show up in the diff.

**Comment by paulolieuthier** [comment]
> The only addition I came across in the meantime is we should probably set the theme to Onyx as this is fitting better default LXQt theme Frost.

We could do it, but technically it's the distribution's job.

**Comment by pmattern** [comment]
@paulolieuthier 
Not following here.
Of course downstream is free to tweak what ever they want. But this shouldn't prevent us from shipping defaults as good as it gets like here a window manager theme that fits the LXQt theme.
Anyway this particular setting was preexisting in the old template `/etc/xdg/openbox/lxqt-rc.xml` so this PR certainly didn't do any harm.

**Comment by paulolieuthier** [comment]
@pmattern OK, you're right. I didn't recall Frost was the default theme.

**Pull request merged**
