### PR TITLE
Update lxqt-rc.xml

### PR DESCRIPTION
**Pull request by stefonarch**
Fix for https://github.com/lxde/lxqt/issues/1032

### CODE REVIEW

**Comment by pmattern** [comment]
Hm, I fear this won't do.
This keyboard shortcut is fixing the main problem in lxde/lxqt#1032 but the file currently used suffers from some additional problems as well, see https://github.com/lxde/lxqt/issues/1032#issuecomment-214572247 (second paragraph).
Couldn't we just copy `/etc/xdg/openbox/rc.xml` as provided by upstream Openbox?

Also, I still think we should change the path to `/etc/xdg/openbox/lxqt-rc.xml` in order to have consistent paths in `$XDG_CONFIG_DIRS` and `$XDG_CONFIG_HOME`, see discussion in lxde/lxqt#1002.

**Comment by stefonarch** [comment]
My idea was  just for now avoid this odd sensation  for new users "Oh, something   does not work" after first login for  the new release. 
Still plenty of time after that to think which version of lxqt-rc.xml to ship.

**Comment by pmattern** [comment]
This is of course an approach that can be taken as well, sure.

**Comment by pmattern** [comment]
Meanwhile I used `rc.xml` as provided by upstream Openbox (md5sum d54f45cfa3ffa34ffc1c99d80902ab09) for a while and couldn't see any downside.
Maybe it does represent the better choice after all.

**Comment by palinek** [comment]
> Meanwhile I used rc.xml as provided by upstream Openbox (md5sum d54f45cfa3ffa34ffc1c99d80902ab09) for a while and couldn't see any downside.
Maybe it does represent the better choice after all.

If we stick with the default configuration provided by openbox w/o any changes, we can remove all our specific default config files and all the copying in startlxqt

**Comment by stefonarch** [comment]
But was it not about users that have already modified their openbox rc.xml which maybe contrasts with default lxqt-shortcuts?

**Comment by LStranger** [comment]
>But was it not about users that have already modified their openbox rc.xml which maybe contrasts with default lxqt-shortcuts?

Users who modify *rc.xml file are always responsible for own changes.

And BTW, saying about Openbox shortcuts - I wrote lxhotkey application
some time ago and asked if someone wants to add a GUI for it, still no
volunteers, does that mean LXQt has another application which adds the
interface to easily change shortcuts in *rc.xml file? Or that was just
missed by everyone? :)

**Comment by stefonarch** [comment]
Not sure abount how users are aware of rc.xml, if some distro ships obconf and the user changes theme or other stuff it's rc.xml which changes.
LXQt is not stuck to openbox, with upcoming wayland it's likely kwin and some others to deal with.

**Comment by pmattern** [comment]
> If we stick with the default configuration provided by openbox w/o any changes, we can remove all our specific default config files and all the copying in startlxqt

You misunderstood. All I did was copy file `/etc/xdg/openbox/rc.xml` to `~/.config/openbox/lxqt-rc.xml` and use it for a while to see whether this is causing problems. This was only done to check whether we could simply replace `/etc/xdg/openbox/lxqt-rc.xml`, which as we all agree isn't really good right now, simply with the one provided by Openbox.

> I wrote lxhotkey application some time ago and asked if someone wants to add a GUI for it

Personally I wasn't aware of it so far. But at first glance this indeed looks as if it could be used as a kind of abstraction layer to configure shortcuts of different window managers from a single GUI and hence certainly like something we should consider.

> Not sure abount how users are aware of rc.xml, if some distro ships obconf and the user changes theme or other stuff it's rc.xml which changes.

No. Obconf is launched with switch `--config-file /home/<user>/.config/openbox/lxqt-rc.xml` and Obconf[-Qt] are sourcing this and writing in this file, too. Are you seeing something different?
Dealing with window managers other than Openbox, e. g. questions like whether there should be a GUI to configure all of them via some kind of abstraction layer, are of course valid but beyond the scope of this PR.

**Comment by stefonarch** [comment]
> Not sure abount how users are aware of rc.xml, if some distro ships obconf and the user changes theme or other stuff it's rc.xml which changes.
>No.

Sure. But I was thinking of lxde users or others who used obconf actually and install lxqt after that.

**Comment by LStranger** [comment]
>> I wrote lxhotkey application some time ago and asked if someone wants to add a GUI for it

>Personally I wasn't aware of it so far. But at first glance this indeed looks as if it could be used as a kind of abstraction layer to configure shortcuts of different window managers from a single GUI and hence certainly like something we should consider.

Yes, that is exactly what I had in mind when wrote it - abstract GUI which can be used for any window manager currently in use, so useful for any DE which does not have own shortcut management tool.
So if it might be useful for LXQt as well then I consider adding it to GitHub and waiting someone to write Qt GUI for it, right?

**Comment by pmattern** [comment]
> Sure. But I was thinking of lxde users or others who used obconf actually and install lxqt after that.

Alright. But note this is not related to this PR any longer. It should go to e. g. lxde/lxqt#1057; I've left a comment there.

> So if it might be useful for LXQt as well then I consider adding it to GitHub and waiting someone to write Qt GUI for it, right?

Personally, I'd be totally in favour of this. The lack of an abstraction layer like this is something I consider missing since I started using LXQt.
But please let's discuss this some where else like in an issue on its own. We guys are right now busy totally cluttering this PR up which isn't really helpful.

**Comment by LStranger** [comment]
>But please let's discuss this some where else like in an issue on its own. We guys are right now busy totally cluttering this PR up which isn't really helpful.

I'm sorry for the noice here. Created an issue lxde/lxqt#1083 for that.

**Comment by pmattern** [comment]
Meanwhile both @stefonarch (see https://github.com/lxde/lxqt/issues/1032#issuecomment-236625815) and me have been testing `/etc/xdg/openbox/rc.xml` as shipped by current Openbox upstream as as replacement of the current `/etc/xdg/openbox/lxqt-rc.xml` shipped by lxqt-common and this seems to work just fine.
So any additional thoughts on this one? Otherwise I'd suggest we replace current `lxqt-rc.xml` that way. This definitely needs to be addressed somehow before we release 0.11.

**Comment by paulolieuthier** [comment]
Could you cook a PR?

**Comment by pmattern** [comment]
Superseded by #59.

**Pull request closed without merging**
