### PR TITLE
LxQt to LXQt renaming

### PR DESCRIPTION
**Pull request by paulolieuthier**

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm

**Comment by paulolieuthier** [comment]
Let's wait for @luis-pereira's CMake-related PRs to be merged.

**Comment by jleclanche** [comment]
This one can land without

**Comment by paulolieuthier** [comment]
This one depends on lxde/lxqt-panel#219, which depends on lxde/liblxqt#50, which is in hold for lxde/liblxqt#51.

**Pull request merged**
