### PR TITLE
Restore the old preferences menu layout of razor-qt.

### PR DESCRIPTION
**Pull request by PCMan**
The "Preferences" menu is a little bit crowded now.
So I tried to restore the old menu layout of razor-qt.
Currently the newly added menu entry is in English.
I'll try to get that entry translated by using the translations in razor-qt.
@jleclanche @luis-pereira @paulolieuthier @pvanek @surlykke @agaida 
Please help review if this change is ok.
Thanks!

### CODE REVIEW

**Comment by jleclanche** [comment]
What does the change look like? I cant test here

**Comment by PCMan** [comment]
BTW, even if you guys like the change, we probably cannot ship this in 0.9 due to string freeze.
I just took a look at razor-qt and found few translated strings for this entry.
In addition, some of the translated strings does not contain "Razor-qt", so `sed -s/Razor-qt/LXQt/g` does not work here. This new menu entry should be translated manually so maybe leave it for 1.0 is better.

**Comment by jleclanche** [comment]
Yes, this won't make 0.9.

**Comment by surlykke** [comment]
2015-01-30 8:33 GMT+01:00 PCMan <notifications@github.com>:

> The "Preferences" menu is a little bit crowded now.
> So I tried to restore the old menu layout of razor-qt.
> Currently the newly added menu entry is in English.
> I'll try to get that entry translated by using the translations in
> razor-qt.
> @jleclanche <https://github.com/jleclanche> @luis-pereira
> <https://github.com/luis-pereira> @paulolieuthier
> <https://github.com/paulolieuthier> @pvanek <https://github.com/pvanek>
> @surlykke <https://github.com/surlykke> @agaida
> <https://github.com/agaida>
> Please help review if this change is ok.
> Thanks!
>
Definitely an improvement IMO.

br. Chr.

**Comment by paulolieuthier** [comment]
@PCMan much, much better.

**Comment by paulolieuthier** [comment]
@jleclanche:
screen

**Comment by luis-pereira** [comment]
I like it. That's an improvement.
And it's An even greater improvement when the user has multiple desktops
environments installed.
--
Luís Pereira
Sent from my Android
No dia 30 de Jan de 2015 21:44, "Paulo Lieuthier" <notifications@github.com>
escreveu:

**Comment by agaida** [comment]
+1, full ack

**Comment by jleclanche** [comment]
gtm, please land it and it will be in 0.9.1

**Comment by pvanek** [comment]
+millions!

**Comment by agaida** [comment]
great, thanks

**Pull request merged**
