### PR TITLE
Set proper prefix for XDG_DATA_DIRS

### PR DESCRIPTION
**Pull request by krytarowski**
Catched and required on pkgsrc / NetBSD.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@krytarowski is this still necessary for your BSD?

**Comment by krytarowski** [comment]
Yes. Maybe there is some macro that will work for use well, GNUInstallDirs.cmake ships with: ``DATAROOTDIR``, will this work for you?

**Comment by paulolieuthier** [comment]
The problem is we set `XDG_DATA_DIRS` to both `/usr/local/share` and `/usr/share`, and you removed it.

**Comment by krytarowski** [comment]
Boths paths are wrong in pkgsrc. Will ``DATAROOTDIR`` expand to ``/usr/share`` and ``/usr/local/share`` for you? I will try to see if there is a generic solution.

**Comment by paulolieuthier** [comment]
> Will DATAROOTDIR expand to /usr/share and /usr/local/share for you?

No. GNUInstallDirs uses the CMake prefix.

**Comment by krytarowski** [comment]
This is all what I get:
https://blogs.kde.org/2008/12/12/how-get-cmake-find-what-you-want-it

Will this work for us? To set ``CMAKE_PREFIX_PATH`` by default to ``/usr/local`` and ``/usr``, and being overwritable from command line (like ``cmake -DCMAKE_PREFIX_PATH=/custom/prefix``).

**Comment by jleclanche** [comment]
@paulolieuthier I agree with this patch. We shouldn't be messing with XDG_DATA_DIRS we don't own in the first place. GTM

**Comment by paulolieuthier** [comment]
OK. I'll test it and merge.

**Comment by luis-pereira** [comment]
Sorry, Didn't notice this.... so many unread stuff.
@jleclanche We are not messing because we are only setting if it's empty.

IMO should be something like this:
```
if [ -z "$XDG_DATA_DIRS" ]; then
    if test "x@_LXQT_DATA_DIR_@" = "x/usr/local/share" -o "x@_LXQT_DATA_DIR_@" = "x/usr/share"; then
        XDG_DATA_DIRS="$XDG_DATA_HOME:/usr/local/share:/usr/share"
    else
        XDG_DATA_DIRS="$XDG_DATA_HOME:@_LXQT_DATA_DIR@:/usr/local/share:/usr/share"
    fi
else
    XDG_DATA_DIRS="$XDG_DATA_DIRS:$XDG_DATA_HOME:@LXQT_DATA_DIR@"
fi
export XDG_DATA_DIRS
```
```LXQT_DATA_DIR``` would be ```CMAKE_INSTALL_FULL_DATADIR``` by default and of course user settable in the command line.

**Comment by paulolieuthier** [comment]
@luis-pereira 
> Sorry, Didn't notice this.... so many unread stuff.

https://addons.mozilla.org/en-us/firefox/addon/github-notifier/ :+1:

**Comment by jleclanche** [comment]
@luis-pereira I don't see why that's more correct, it seems very unnecessary. I'm still +1 on the PR here.

**Comment by krytarowski** [comment]
I'm not a FreeBSD representative but they may want to install software from ports, just to ``/usr/local``, without messing with base ``/usr/share``. This helps them (in theory) to keep the same set of packages and replace base.

Linux stuff mostly goes under the prefix ``/usr``, where ``/usr/local`` is for locally built packages.

I sympathize with jleclanche to keep single prefix in the default installation. If someone can maintain his or her own alternative prefix then will likely be able to add the path manually in the LXQt configs.

**Comment by paulolieuthier** [comment]
@krytarowski the problem is that from the [spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), if `XDG_DATA_DIRS` is not set, the value `/usr/local/share:/usr/share` should be used. I'm afraid that if we set it to `/usr/local/share` only we'll break something. But maybe I'm saying nonsense. @PCMan what do you think?

**Comment by krytarowski** [comment]
The same applies for ``XDG_CONFIG_DIRS``, ``/usr/`` + ``/usr/local`` and ``/etc/xdg`` are Linux standard base centric.

"If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used. " -- from the same spec.

And we go platform specific paths for it.

```
if [ -z "$XDG_CONFIG_DIRS" ]; then
        export XDG_CONFIG_DIRS="$XDG_CONFIG_HOME:/usr/pkg/etc/xdg/"
fi
```

**Comment by jleclanche** [comment]
@paulolieuthier the patch currently sets it to the cmake prefix, which would *just* be `/usr` in most cases, so it works out great.

**Comment by paulolieuthier** [comment]
I just tested the patch, installing LXQt in `/usr/local`. A lot of things are broken, notably icons, menu and runner applications search. It must have both `/usr/share` and `${CMAKE_INSTALL_PREFIX}/share` (which in my case is `/usr/local/share`).

**Comment by jleclanche** [comment]
I still think that's correct but will need to think more about it.

**Comment by krytarowski** [comment]
I will be fully satisfied if there will be an option to set ``LXQT_XDG_DATA_DIRS`` from command line parameter or an environment value, defaulting it to ``/usr/local/share/`` and ``/usr/share/``, doing what the XDG spec says.

Then the new ``startlxqt.in`` line will look this way:

```
export XDG_DATA_DIRS="$XDG_DATA_HOME:@LXQT_XDG_DATA_DIRS@"
```

It will be remarked just by downstream already patching it (like the pkgsrc one). It will also make life easier for those installing under custom prefix, like to ``/opt``.

**Comment by krytarowski** [comment]
We can add a configure warning for all those installing it to a different prefix than ``/usr`` or ``/usr/local``, just to to not overlook it.

**Comment by luis-pereira** [comment]
@jleclanche With an empty ```XDG_DATA_DIRS```, ```/usr/loca/share``` and ```/usr/share``` will be searched (they are the default). If we set ```XDG_DATA_DIRS``` to something and do not add ```/usr/local/share``` and ```/usr/share``` , the default locations will not be searched. The issue is that we can install LXQt to something like ```/opt``` but other programs can be installed in, say, ```/usr```.
__If the default locations are not added we are actually "subtracting" them.__

The idea behind my code is that if we get an empy ```XDG_DATA_DIRS``` and set it to something we add the default locations.  Most DE's do that, probably all.

**Comment by krytarowski** [comment]
@luis-pereira I much prefer to handle these options in the configure part. In this case ``startlxqt`` will be ready as preprocessed for the installed system. If someone will try to edit it later will likely need to remove all the logic and just set the proper variable. All users who want to keep ``/usr`` and ``/usr/local`` separate will need to do it as well.

**Comment by luis-pereira** [comment]
@krytarowski Not sure If I understood you correctly. The starlxqt.in is processed at configure time. But it can't be static because we don't know in what environment it will run.

**Comment by paulolieuthier** [comment]
@luis-pereira I'm trying to make your snippet more complete, this is what I've done.

```
if [ -z "$XDG_DATA_DIRS" ]; then
    if test "x@_LXQT_DATA_DIR_@" = "x/usr/local/share" -o "x@_LXQT_DATA_DIR_@" = "x/usr/share"; then
        XDG_DATA_DIRS="$XDG_DATA_HOME:/usr/local/share:/usr/share"
    else
        XDG_DATA_DIRS="$XDG_DATA_HOME:@_LXQT_DATA_DIR@:/usr/local/share:/usr/share"
    fi
else
    if [ -n "$XDG_DATA_HOME" ] && [[ $XDG_DATA_DIRS != *$XDG_DATA_HOME* ]]; then
        XDG_DATA_DIRS="$XDG_DATA_DIRS:$XDG_DATA_HOME"
    fi
    if [[ $XDG_DATA_DIRS != *@LXQT_DATA_DIR@* ]]; then
        XDG_DATA_DIRS="$XDG_DATA_DIRS:@LXQT_DATA_DIR@"
    fi
fi
export XDG_DATA_DIRS
```

I just changed the else branch. That was in order to avoid duplicate paths in `XDG_DATA_DIRS`, since that might mean uncessary time looking for icons and fonts etc. What do you think?

**Comment by luis-pereira** [comment]
@paulolieuthier 
> if [ -n "$XDG_DATA_HOME" ] && [[ $XDG_DATA_DIRS != *$XDG_DATA_HOME* ]]; then

```-n "$XDG_DATA_HOME"``` always evaluate to ```true```. ```XDG_DATA_HOME``` was previously set here https://github.com/lxde/lxqt-common/blob/master/startlxqt.in#L4.

Other then that I don't foresee any issue, but as always we need to test it.

**Comment by paulolieuthier** [comment]
> -n "$XDG_DATA_HOME" always evaluate to true. XDG_DATA_HOME was previously set here

Right.

> Other then that I don't foresee any issue, but as always we need to test it.

I'll test it, sure. Then @krytarowski, if possible.

**Comment by krytarowski** [comment]
Please push it to a branch and I will test it.

**Comment by paulolieuthier** [comment]
@luis-pereira:
> LXQT_DATA_DIR would be CMAKE_INSTALL_FULL_DATADIR by default.

This is still to be done, right?

**Comment by krytarowski** [comment]
Yes

**Comment by paulolieuthier** [comment]
liblxqt only defines `LXQT_ETC_XDG_DIR` as I can see. @luis-pereira can you work on it?

**Comment by palinek** [comment]
>
```
if [ -z "$XDG_DATA_DIRS" ]; then
    if test "x@_LXQT_DATA_DIR_@" = "x/usr/local/share" -o "x@_LXQT_DATA_DIR_@" = "x/usr/share"; then
        XDG_DATA_DIRS="$XDG_DATA_HOME:/usr/local/share:/usr/share"
    else
        XDG_DATA_DIRS="$XDG_DATA_HOME:@_LXQT_DATA_DIR@:/usr/local/share:/usr/share"
    fi
else
    if [ -n "$XDG_DATA_HOME" ] && [[ $XDG_DATA_DIRS != *$XDG_DATA_HOME* ]]; then
        XDG_DATA_DIRS="$XDG_DATA_DIRS:$XDG_DATA_HOME"
    fi
    if [[ $XDG_DATA_DIRS != *@LXQT_DATA_DIR@* ]]; then
        XDG_DATA_DIRS="$XDG_DATA_DIRS:@LXQT_DATA_DIR@"
    fi
fi
export XDG_DATA_DIRS
```

@paulolieuthier @luis-pereira why are you mixing the test notation?
In one place using the plain test command notation on other the 'shortcut' [ and also the "bash specific" [[.
Is the script supposed to run with sh or is just with bash?

**Comment by luis-pereira** [comment]
@paulolieuthier liblxqt `LXQT_DATA_DIR` definition taken care at https://github.com/lxde/liblxqt/commit/06d4bbb69fd0d06cba41b7de725663a7dd20da37
@palinek My snippet should have been in _pseudo code_.  Didn't pay attention to the style or anything else other than the idea behind the code.  We must avoid bashisms of course.

**Comment by paulolieuthier** [comment]
Nice. I'll test it.

**Comment by paulolieuthier** [comment]
@luis-pereira I installed liblxqt in `/opt/lxqt` using `-DLXQT_DATA_DIR`. Then, in order to lxqt-common to find it, I have to run `cmake .. -DCMAKE_PREFIX_PATH=/opt/lxqt`. Is that ther right way? If so, we can merge it.

**Comment by luis-pereira** [comment]
@paulolieuthier What do you mean with "....in order to lxqt-common find it" ? finding liblxqt or getting the `LXQT_DATA_DIR` value ?
Sorry for the delayed responses.

**Comment by paulolieuthier** [comment]
@luis-pereira the only way to make lxqt-common find liblxqt (and thus be able to get `LXQT_DATA_DIR`) I have to specify `CMAKE_PREFIX_PATH=/opt/lxqt`. If I don't do that, liblxqt won't be found and CMake will throw an error. I just want to know if this is the intended behaviour.

**Comment by luis-pereira** [comment]
@paulolieuthier No, `cmake -DCMAKE_INSTALL_PREFIX=/opt/lxqt ..` should do it. And it did on my tests. Pls note that `find_package()` starts by searching in the system standard dirs (/usr/local;/usr). If you have another liblxqt installed there, it stops and never gets to the `CMAKE_INSTALL_PREFIX`

**Comment by paulolieuthier** [comment]
> If you have another liblxqt installed there, it stops and never gets to the `CMAKE_INSTALL_PREFIX`

Yep, I removed liblxqt from /usr/local before testing.

> @paulolieuthier No, `cmake -DCMAKE_INSTALL_PREFIX=/opt/lxqt` .. should do it. And it did on my tests.

On my tests I installed liblxqt in /opt/lxqt and was trying to install lxqt-common on /usr/local, that's probably why it didn't work.

**Comment by paulolieuthier** [comment]
@krytarowski, please update your PR:

```diff
diff --git a/startlxqt.in b/startlxqt.in
index 2bfa29a..3bdfc3d 100755
--- a/startlxqt.in
+++ b/startlxqt.in
@@ -9,8 +9,20 @@ if [ -z "$XDG_CONFIG_HOME" ]; then
 fi
 
 if [ -z "$XDG_DATA_DIRS" ]; then
-	export XDG_DATA_DIRS="$XDG_DATA_HOME:@CMAKE_INSTALL_PREFIX@/share/"
+    if [ "x@LXQT_DATA_DIR@" = "x/usr/local/share" ] || [ "x@_LXQT_DATA_DIR_@" = "x/usr/share" ]; then
+        XDG_DATA_DIRS="$XDG_DATA_HOME:/usr/local/share:/usr/share"
+    else
+        XDG_DATA_DIRS="$XDG_DATA_HOME:@LXQT_DATA_DIR@:/usr/local/share:/usr/share"
+    fi
+else
+    if [[ $XDG_DATA_DIRS != *$XDG_DATA_HOME* ]]; then
+        XDG_DATA_DIRS="$XDG_DATA_DIRS:$XDG_DATA_HOME"
+    fi
+    if [[ $XDG_DATA_DIRS != *@LXQT_DATA_DIR@* ]]; then
+        XDG_DATA_DIRS="$XDG_DATA_DIRS:@LXQT_DATA_DIR@"
+    fi
 fi
+export XDG_DATA_DIRS
 
 # Ensure the existance of the 'Desktop' folder
 if [ -e "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
```

**Comment by palinek** [comment]
>
```diff
+    if [[ $XDG_DATA_DIRS != *$XDG_DATA_HOME* ]]; then
+        XDG_DATA_DIRS="$XDG_DATA_DIRS:$XDG_DATA_HOME"
+    fi
+    if [[ $XDG_DATA_DIRS != *@LXQT_DATA_DIR@* ]]; then
+        XDG_DATA_DIRS="$XDG_DATA_DIRS:@LXQT_DATA_DIR@"
+    fi
```

...and avoid bash specific tests `[[`

**Comment by paulolieuthier** [comment]
@palinek I don't know how to do it without those double brackets.

**Comment by palinek** [comment]
how about old dummy one:
```bash
if echo "$XDG_DATA_DIRS" | grep -q "@LXQT_DATA_DIR@"; then
```

**Comment by jleclanche** [comment]
That's not better, it creates a dependency on both echo and grep.

**Comment by jleclanche** [comment]
BTW remember to quote all variables. There might be spaces in them.

**Comment by palinek** [comment]
> That's not better, it creates a dependency on both echo and grep.

well... but it's used all over e.g. also in /usr/bin/startx:
```bash
    tty=$(tty)
    if expr match "$tty" '^/dev/tty[0-9]\+$' > /dev/null; then
        tty_num=$(echo "$tty" | grep -oE '[0-9]+$')
        vtarg="vt$tty_num"
    fi
...
    if hostname --version > /dev/null 2>&1; then
        if [ -z "`hostname --version 2>&1 | grep GNU`" ]; then
            hostname=`hostname -f`
        fi
    fi

**Comment by jleclanche** [comment]
We ship in places where startx isn't used.

**Comment by krytarowski** [comment]
Thanks! ``echo`` and ``grep`` are widely used in most (all?) pkgsrc platforms. I will check whether it can be reduced to pure NetBSD sh(1).

**Comment by jleclanche** [comment]
`printf` can safely be used instead of `echo`. As for grep, if there's a way to avoid it, let's.

**Comment by palinek** [comment]
We can make this check also this way
```sh
if ! [ "$XDG_DATA_DIRS" = '@LXQT_DATA_DIR@' -o -z "${XDG_DATA_DIRS##@LXQT_DATA_DIR@:*}" -o -z "${XDG_DATA_DIRS##*:@LXQT_DATA_DIR@:*}" -o -z "${XDG_DATA_DIRS%%*:@LXQT_DATA_DIR@}" ]; then
...
```
Note that all the previous solutions were a bit broken because of preffix/suffix possibility (we must check all possibilities -> only one dir, dir on the begginning, in the middle, at the end)

**Comment by paulolieuthier** [comment]
@palinek can you please take care of this (since you are a ancient-shell ninja)? Simply commit it and we can close this PR.

**Comment by palinek** [comment]
@paulolieuthier, @krytarowski just pushed te discussed change into #36, but didn't test it. Please, take care of the testing.

**Comment by paulolieuthier** [comment]
GTM.

**Comment by palinek** [comment]
@paulolieuthier good to merge is this PR... or the #36?

**Comment by paulolieuthier** [comment]
Oops. #36, sorry.

**Comment by krytarowski** [comment]
Thank you!

**Pull request closed without merging**
