### PR TITLE
Add lxqt-leave.directory

### PR DESCRIPTION
**Pull request by dbluelle**
Fixes lxde/lxqt#454 and fixes lxde/lxqt#437.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@dbluelle please, squash the commits.

**Comment by dbluelle** [comment]
OK, done

**Comment by paulolieuthier** [comment]
Thank you :smile:

**Comment by jleclanche** [comment]
Thanks!

**Comment by agaida** [comment]
Thanks!

**Pull request merged**
