### PR TITLE
Added simple theme files for lxqt-sudo

### PR DESCRIPTION
**Pull request by stefonarch**
schermata08
schermata07
schermata06

### CODE REVIEW

**Comment by jleclanche** [comment]
This looks pretty awful tbh, I think we're better off with the default theming...

**Comment by paulolieuthier** [comment]
I agree. And the warning about missing theme file is just a warning, it's not necessary to fix it.

**Comment by agaida** [comment]
an empty file would do the trick, wouldn't it?

**Comment by stefonarch** [comment]
Five empty files, for each theme one.
But at this point why not match the appearance from lxqt-runner and panel   from chosen theme as I proposed?

**Comment by agaida** [comment]
don't understand - the empty files would hopefully silence the useless warnings which i hate - and this is not only a academical point of view - a warning has to be shown, when things can go wrong. A warning that document intended behaviour is misguiding - and if things goes wrong i have to tell the users that the warning means nothing - again and again and again - and this sucks a lot :)

**Comment by jleclanche** [comment]
The warnings should be removed, we discussed this before. No empty file to add.

**Pull request closed without merging**
