### PR TITLE
Place LXQt About over Preferences in the main menu

### PR DESCRIPTION
**Pull request by agaida**
make lxde/lxqt-about/pull/5 obsolete

### CODE REVIEW

**Comment by paulolieuthier** [comment]
GTM.

**Comment by jleclanche** [comment]
Can you respect the tab indents of the file please.

**Comment by pmattern** [comment]
Placing that new topic "about" *below* menu "Preferences" would look a bit better, imho.

**Comment by agaida** [comment]
ok - we can try that

**Comment by agaida** [comment]
ok - whitespaces fixed, sorry, copied in nano
placed About below Preferences

any other changes/suggestions needed?

**Comment by paulolieuthier** [comment]
GTM.

**Comment by pmattern** [comment]
Everyone who took a look so far thinks its okay, hence merging.

**Pull request merged**
